version: 2
jobs:
  build:
    docker:
      - image: golang:1.11
    working_directory: /go/src/github.com/jukeizu/contract
    steps:
      - checkout
      - run: go vet
      - run: go test -v -race
